backend:
  name: git-gateway
  branch: dev
media_folder: images/upload
collections:
- name: "note"
  label: "Note"
  folder: "src"
  create: true
  fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Tags", name: "tags", widget: "list", default: ["devops", "backend", "systemdesign"] }
    - { label: "Body", name: "body", widget: "markdown" }